### ISSUE TITLE
websocket Exception: socket is already closed

### ISSUE THREAD

**Issue by toints** [websocket-client/websocket-client#281]
when I use websocket-client to send json data,   occurred this mistake:

Traceback (most recent call last):
File "test.py", line 22, in 
self.ws.send(json_dumps(data))
File "/opt/anaconda/lib/python2.7/site-packages/websocket_client-0.39.0-py2.7.egg/websocket/_app.py", line 117, in send
if not self.sock or self.sock.send(data, opcode) == 0:
File "/opt/anaconda/lib/python2.7/site-packages/websocket_client-0.39.0-py2.7.egg/websocket/_core.py", line 234, in send
return self.send_frame(frame)
File "/opt/anaconda/lib/python2.7/site-packages/websocket_client-0.39.0-py2.7.egg/websocket/_core.py", line 259, in send_frame
l = self._send(data)
File "/opt/anaconda/lib/python2.7/site-packages/websocket_client-0.39.0-py2.7.egg/websocket/_core.py", line 423, in _send
return send(self.sock, data)
File "/opt/anaconda/lib/python2.7/site-packages/websocket_client-0.39.0-py2.7.egg/websocket/_socket.py", line 113, in send
raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.

Anyone else has encounted, or how to solve this problem ? thank you.

**Comment by liris** [comment]
Did you close the socket before "send" command?

**Comment by tux-00** [comment]
In my case, the issue happens when I disable my network connection.

**Comment by nitishxp** [comment]
`import websocket
from camera import VideoCamera
try:
    import threading
except ImportError:
    import _thread as thread


def on_message(ws, messge):
    print(messge)


def connect(ws):
    camera = VideoCamera()
    while True:
        frame = camera.get_frame()
        ws.send(b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')


def on_open(ws):
    thread_var = threading.Thread(
        name="connect_thread", target=connect, args=(ws, ))
    thread_var.start()


def on_error(ws, error):
    print("error", error)


if __name__ == '__main__':
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp(
        "%s/device/%s/" % ('xxx.xx.com', 1),
        on_message=on_message,
        on_error=on_error,
    )
    ws.on_open = on_open
    ws.run_forever(ping_interval=6, ping_timeout=5)`

**Comment by nitishxp** [comment]
`
import websocket
from camera import VideoCamera
try:
    import threading
except ImportError:
    import _thread as thread


def on_message(ws, messge):
    print(messge)


def connect(ws):
    camera = VideoCamera()
    while True:
        frame = camera.get_frame()
        ws.send(b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')


def on_open(ws):
    thread_var = threading.Thread(
        name="connect_thread", target=connect, args=(ws, ))
    thread_var.start()


def on_error(ws, error):
    print("error", error)


if __name__ == '__main__':
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp(
        "%s/device/%s/" % ('xxx.xx.com', 1),
        on_message=on_message,
        on_error=on_error,
    )
    ws.on_open = on_open
    ws.run_forever(ping_interval=6, ping_timeout=5)
`

I am getting this error

\xd9b\\\x97\xd9b\\\x97\xd9b\\\x97\xd9b\\\x97\xd9b\\\x97\xd9b\\\x97\xd9b\\\x97\xd9b\\@\xa2\xe5V\xb2q'
Exception in thread connect_thread:
  File "d:\users\nitish\appdata\local\programs\python\python37-32\Lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "d:\users\nitish\appdata\local\programs\python\python37-32\Lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File ".\main.py", line 26, in connect
    b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')
  File "C:\Users\Nitish\envs\py3\lib\site-packages\websocket\_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "C:\Users\Nitish\envs\py3\lib\site-packages\websocket\_core.py", line 250, in send
    return self.send_frame(frame)
    l = self._send(data)
  File "C:\Users\Nitish\envs\py3\lib\site-packages\websocket\_core.py", line 445, in _send
    return send(self.sock, data)
  File "C:\Users\Nitish\envs\py3\lib\site-packages\websocket\_socket.py", line 114, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.

**Comment by engn33r** [comment]
The error message indicates that the server closed the connection. You can try to use a periodic ping ([see project documentation](https://websocket-client.readthedocs.io/en/latest/examples.html#ping-pong-usage)) to keep the connection alive and avoid this issue. If using ping does not work, you will either need to contact the WebSocket server owner to understand why the server closed the connection, or find an alternative (such as checking whether the connection is alive before sending data).
