### ISSUE TITLE
WebSocketPayloadException under high traffic and limited network connection

### ISSUE THREAD

**Issue by juhhov** [websocket-client/websocket-client#306]
Steps to reproduce:
- Produce high volume traffic between socketIO server and client
- Limit the network connection with a tool such as [http://manpages.ubuntu.com/manpages/wily/man8/wondershaper.8.html](url)
- After a timeout following kind of trace is shown:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.7.2-py2.7.egg/socketIO_client/__init__.py", line 260, in wait
    self._process_packets()
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.7.2-py2.7.egg/socketIO_client/__init__.py", line 286, in _process_packets
    for engineIO_packet in self._transport.recv_packet():
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.7.2-py2.7.egg/socketIO_client/transports.py", line 151, in recv_packet
    packet_text = self._connection.recv()
  File "/usr/local/lib/python2.7/dist-packages/websocket_client-0.40.0-py2.7.egg/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/usr/local/lib/python2.7/dist-packages/websocket_client-0.40.0-py2.7.egg/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/local/lib/python2.7/dist-packages/websocket_client-0.40.0-py2.7.egg/websocket/_core.py", line 334, in recv_data_frame
    return self.cont_frame.extract(frame)
  File "/usr/local/lib/python2.7/dist-packages/websocket_client-0.40.0-py2.7.egg/websocket/_abnf.py", line 420, in extract
    "cannot decode: " + repr(frame.data))
WebSocketPayloadException: cannot decode: '\x81~\x01\xe542["resource_stats",{"resource_id":"7de45fc0-0fb7-11e7-ba6b-23cb58f59eff","uptime":{"appeared":52.162,"application":52.202},"io":{"read":21415,"written":443},"operations":{'
```

Instead of such exception TimeoutError should be raised.

**Comment by juhhov** [comment]
This commit seems to fix the WebSocketPayloadException:
https://github.com/ARMmbed/websocket-client/commit/bc2d767fa3669215cb8594309cc01a0879715201
