### ISSUE TITLE
recv() return empty '' when server closed the connection?

### ISSUE THREAD

**Issue by sejust** [websocket-client/websocket-client#310]
hi:
    I want to receive iterable message from the server, but the last message I got was empty string '' after the server closed the connection.

raise WebSocketConnectionClosedException when receiving if the connection is closed ?

here is my simple testing code:
server:
```python
def iter_mes(channel):

    for i in xrange(3):
        if i == 2:
            channel.ws.close()
        else:
            channel.ws.send(str(i))
            time.sleep(5)

class TestWebSocketApplication(WebSocketApplication):

    def on_message(self, message):

        th_server = threading.Thread(target=iter_mes, args=(self,))
        th_server.daemon = True
        th_server.start()

        return
```

client 1:
```python

cli = make_cli()
cli.send('')

for mes in cli:
    print 'is connected: ', cli.connected
    print 'received: `{mes}`'.format(mes=mes)
```

message 1:
```txt
is connected:  True
received: `0`
is connected:  True
received: `1`
is connected:  False
received: ``
Traceback (most recent call last):
  File "ccc.py", line 8, in <module>
    for mes in cli:
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 105, in __iter__
    yield self.recv()
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/lib/python2.7/site-packages/websocket/_abnf.py", line 336, in recv_frame
    self.recv_header()
  File "/usr/lib/python2.7/site-packages/websocket/_abnf.py", line 286, in recv_header
    header = self.recv_strict(2)
  File "/usr/lib/python2.7/site-packages/websocket/_abnf.py", line 371, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "/usr/lib/python2.7/site-packages/websocket/_socket.py", line 93, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
```

client 2:
```python

cli = make_cli()
cli.send('')

while True:
    print 'is connected: ', cli.connected
    print 'received: `{mes}`'.format(mes=cli.recv())
```

message 2:
```txt
is connected:  True
received: `0`
is connected:  True
received: `1`
is connected:  True
received: ``
is connected:  False
Traceback (most recent call last):
  File "ccc.py", line 10, in <module>
    print 'received: `{recv}`'.format(recv=cli.recv())
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/lib/python2.7/site-packages/websocket/_abnf.py", line 336, in recv_frame
    self.recv_header()
  File "/usr/lib/python2.7/site-packages/websocket/_abnf.py", line 286, in recv_header
    header = self.recv_strict(2)
  File "/usr/lib/python2.7/site-packages/websocket/_abnf.py", line 371, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "/usr/lib/python2.7/site-packages/websocket/_socket.py", line 93, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
```

**Comment by punnerud** [comment]
You get this error if the server is using SSL

`import ssl`

And changed the last part to:
```
if __name__ == "__main__":
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp(api_url: 'wss://api.example.com',
                              header = header, 
                              on_message = on_message,
                              on_error = on_error,
                              on_close = on_close)
    ws.on_open = on_open
    ws.run_forever(sslopt={"cert_reqs": ssl.CERT_NONE, "check_hostname": False})
```
