### ISSUE TITLE
Websocket unexplainably breaks.

### ISSUE THREAD

**Issue by nichoski** [websocket-client/websocket-client#324]
My script that is using websocket-clients breaks, and I'm not exactly sure what is happening. Can I get some explanation please?
On the server end, I only get this message "Problem occurred during websocket write, websocket closed".

Here is the traceback of the problem:

Traceback (most recent call last):
  File "ari_service.py", line 10, in <module>
    app.connect()
  File "/home/user/pbx_project/pbx_project/ari/models.py", line 195, in connect
    for response_str in iter(lambda: ws.recv(), None):
  File "/home/user/pbx_project/pbx_project/ari/models.py", line 195, in <lambda>
    for response_str in iter(lambda: ws.recv(), None):
  File "/usr/lib64/python3.4/site-packages/websocket/_core.py", line 298, in recv
    opcode, data = self.recv_data()
  File "/usr/lib64/python3.4/site-packages/websocket/_core.py", line 315, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/lib64/python3.4/site-packages/websocket/_core.py", line 328, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/lib64/python3.4/site-packages/websocket/_core.py", line 360, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/lib64/python3.4/site-packages/websocket/_abnf.py", line 312, in recv_frame
    self.recv_header()
  File "/usr/lib64/python3.4/site-packages/websocket/_abnf.py", line 261, in recv_header
    header = self.recv_strict(2)
  File "/usr/lib64/python3.4/site-packages/websocket/_abnf.py", line 346, in recv_strict
    bytes = self.recv(min(16384, shortage))
  File "/usr/lib64/python3.4/site-packages/websocket/_core.py", line 429, in _recv
    return recv(self.sock, bufsize)
  File "/usr/lib64/python3.4/site-packages/websocket/_socket.py", line 89, in recv
    raise WebSocketConnectionClosedException("Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

**Comment by liris** [comment]
It seems other thread has already disconnect the socket

**Comment by nichoski** [comment]
Liris, by 'other thread', do you mean the server?

**Comment by liris** [comment]
not only server, network problem or something has happened and the sock has been closed.

please set the logging level to debug.

**Comment by engn33r** [comment]
Closing this issue because it is stale and has been answered as best as possible with the provided information. If a more detail answer would be helpful, please post the full communication sequence after [enabling debug logging](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) in your code.

This specific error message is captured [in the FAQ](https://websocket-client.readthedocs.io/en/latest/faq.html#how-to-solve-the-connection-is-already-closed-error), and the [project documentation on threading](https://websocket-client.readthedocs.io/en/latest/threading.html) may have some useful threading information.
