### ISSUE TITLE
(Regression) TypeError: cafile, capath and cadata cannot be all omitted

### ISSUE THREAD

**Issue by duizendnegen** [websocket-client/websocket-client#330]
`websocket-client` 0.43 fails (when used through Docker Cloud CLI). Explicitly pointing to an earlier version by running `pip install websocket-client==0.40 docker-cloud` fixes this.

```Traceback (most recent call last):
  File "/usr/local/bin/docker-cloud", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/dockercloudcli/cli.py", line 301, in main
    dispatch_cmds(args)
  File "/usr/local/lib/python2.7/dist-packages/dockercloudcli/cli.py", line 116, in dispatch_cmds
    commands.container_exec(args.identifier, args.command)
  File "/usr/local/lib/python2.7/dist-packages/dockercloudcli/commands.py", line 558, in container_exec
    invoke_shell(url)
  File "/usr/local/lib/python2.7/dist-packages/dockercloudcli/commands.py", line 449, in invoke_shell
    shell = websocket.create_connection(url, timeout=10, header=h)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 487, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 211, in connect
    options.pop('socket', None))
  File "/usr/local/lib/python2.7/dist-packages/websocket/_http.py", line 77, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_http.py", line 182, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_http.py", line 138, in _wrap_sni_socket
    context.load_verify_locations(cafile=sslopt.get('ca_certs', None), capath=sslopt.get('ca_cert_path', None))```

**Comment by duizendnegen** [comment]
Might have to do with https://github.com/websocket-client/websocket-client/pull/316

**Comment by liris** [comment]
please try 0.44.0

**Comment by duizendnegen** [comment]
Fix confirmed, thanks.
