### ISSUE TITLE
create_connection can not import in python 3.4

### ISSUE THREAD

**Issue by sahdev0** [websocket-client/websocket-client#366]
I am connecting with bitfinex.com to get live trade stream data using "wss://api2.bitfinex.com:3000/ws" websocket. But when i installed websocket_client using python3.4 pip and run the following code 

```
import json

from websocket import create_connection

ws = create_connection("wss://api.bitfinex.com/ws/2")
#ws.connect("wss://api2.bitfinex.com:3000/ws")
ws.send(json.dumps({
    "event": "subscribe",
    "channel": "book",
    "symbol": "tBTCUSD",
}))


while True:
    result = ws.recv()
    result = json.loads(result)
    xxx = result
    print(xxx[0])
    #print(result[1])

ws.close()
```

But i am getting following error in console:

```
Traceback (most recent call last):
  File "D:/bitstamp/socket.py", line 3, in <module>
    from websocket import create_connection
  File "C:\Python34\lib\site-packages\websocket_client-0.44.0-py3.4.egg\websocket\__init__.py", line 23, in <module>
    from ._app import WebSocketApp
  File "C:\Python34\lib\site-packages\websocket_client-0.44.0-py3.4.egg\websocket\_app.py", line 35, in <module>
    from ._core import WebSocket, getdefaulttimeout
  File "C:\Python34\lib\site-packages\websocket_client-0.44.0-py3.4.egg\websocket\_core.py", line 24, in <module>
    import socket
  File "D:\bitstamp\socket.py", line 3, in <module>
    from websocket import create_connection
ImportError: cannot import name 'create_connection'
```

Is their any issue with websocket_client for python 3.4 or any error on my python code

**Comment by liris** [comment]
I think "D:/bitstamp/socket.py" override socket.py of python standard library.
