### ISSUE TITLE
OSError: [WinError 10042] when making connection (windows?)

### ISSUE THREAD

**Issue by Yuanchu** [websocket-client/websocket-client#370]
Encountered an error when doing
`ws = create_connection(url)`
Error message below:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\think\websocket-client\websocket\_core.py", line 487, in create_connection
    websock.connect(url, **options)
  File "C:\Users\think\websocket-client\websocket\_core.py", line 211, in connect
    options.pop('socket', None))
  File "C:\Users\think\websocket-client\websocket\_http.py", line 71, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "C:\Users\think\websocket-client\websocket\_http.py", line 108, in _open_socket
    sock.setsockopt(*opts)
OSError: [WinError 10042] An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call

**Comment by liris** [comment]
I don't have windows machine, at all? Does anyone know about this?

**Comment by leovp** [comment]
Here option `TCP_KEEPCNT` is set, but it's not supported on Windows: https://github.com/websocket-client/websocket-client/blob/430d1dcb860fc1ce7ee841c905bc1cce3d5a7448/websocket/_socket.py#L38

Check for a `sys.platform == 'win32'` as well is the shortest fix possible.

**Comment by elgplayer** [comment]
Having similair issue:
`url = 'wss://updates2.bitcointicker.co:8080/socket.io/?EIO=3&transport=websocket&sid=ITQlG3kj4gWOp2tUBjl1'

import websocket
ws = websocket.WebSocket()
ws.connect(url)

Traceback (most recent call last):

  File "<ipython-input-31-31eb6115cc72>", line 3, in <module>
    ws.connect(url)

  File "C:\Users\Carl-Windows\AppData\Local\Programs\Python\Python36\lib\site-packages\websocket\_core.py", line 211, in connect
    options.pop('socket', None))

  File "C:\Users\Carl-Windows\AppData\Local\Programs\Python\Python36\lib\site-packages\websocket\_http.py", line 71, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)

  File "C:\Users\Carl-Windows\AppData\Local\Programs\Python\Python36\lib\site-packages\websocket\_http.py", line 108, in _open_socket
    sock.setsockopt(*opts)

OSError: [WinError 10042] An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call`


`sys.platform == 'win32'
Out[32]: True`

**Comment by Yuanchu** [comment]
Ok. I switched to Mac. Turned out WebSocket is only supported by Window 8+.

**Comment by animalize** [comment]
This is a bug of Python 3.6.4, https://bugs.python.org/issue32394

There are two solutions:
1. Upgrade to Windows 10 1703+, which supports `TCP_KEEPCNT` flag.
2. Use Python 3.6.3 (always hide `TCP_KEEPCNT` flag), or Use Python 3.6.5+ (hide `TCP_KEEPCNT` flag on unusable Windows).

**Comment by kiwirot** [comment]
> This is a bug of Python 3.6.4, https://bugs.python.org/issue32394

Thank you so much. I got the same error message and never expected a bug in Python. Now everything works fine. :+1: 

_Backgroud for other users_
OS: Win 7 x64
Python 3.6.4
Error Msg: [WinError 10042] Beim Aufruf von getsockopt oder setsockopt wurde eine nicht unterstützte Option bzw. Ebene angegeben
