### ISSUE TITLE
Exception when connecting: Address family not supported by protocol

### ISSUE THREAD

**Issue by pdonis** [websocket-client/websocket-client#382]
I am seeing the following exception repeatedly when using create_connection:

Traceback (most recent call last):
  File "websocket/_core.py", line 487, in create_connection
  File "websocket/_core.py", line 211, in connect
  File "websocket/_http.py", line 71, in connect
  File "websocket/_http.py", line 105, in _open_socket
  File "/usr/lib/python2.7/socket.py", line 187, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 124] Address family not supported by protocol

As far as I can tell, this is happening because _open_socket is creating a socket with just the family argument passed, and it's trying every possible family from the list of results returned by getaddrinfo. This does not seem like a good idea since the socket constructor has type and protocol arguments whose default values might not match the family; all of these arguments should be taken from the getaddrinfo return value. Working on a patch.

**Comment by pdonis** [comment]
Submitted pull request #383

**Comment by liris** [comment]
merged #383
