### ISSUE TITLE
Invalid error code (_ssl.c:2217)

### ISSUE THREAD

**Issue by lowkey2016** [websocket-client/websocket-client#392]
When I use this lib, my client got these exceptions, can anyone fix this?

Traceback (most recent call last):
  File "/Users/apple/Desktop/leekhunter/collectors/ws2.py", line 60, in connect
    message = self.ws.recv()
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/local/lib/python3.6/site-packages/websocket/_abnf.py", line 340, in recv_frame
    self.recv_header()
  File "/usr/local/lib/python3.6/site-packages/websocket/_abnf.py", line 288, in recv_header
    header = self.recv_strict(2)
  File "/usr/local/lib/python3.6/site-packages/websocket/_abnf.py", line 375, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "/usr/local/lib/python3.6/site-packages/websocket/_socket.py", line 80, in recv
    bytes_ = sock.recv(bufsize)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 994, in recv
    return self.read(buflen)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 633, in read
    v = self._sslobj.read(len)
ssl.SSLError: Invalid error code (_ssl.c:2217)

**Comment by liris** [comment]
It looks ssl library issue.

**Comment by shdown** [comment]
@liris, it very much looks like **your** issue. Providing your own `certs.pem` is a **horribly bad decision**. This is basically compromising the security of whoever uses your library.

To @lowkey2016 and whoever else runs into this problem.

The quick fix is, assuming you are on a Linux system, is to set `WEBSOCKET_CLIENT_CA_BUNDLE` to `/etc/ssl/certs`.

You can put `export WEBSOCKET_CLIENT_CA_BUNDLE=/etc/ssl/certs` into your shell’s rc file, or, if you want it to be system-wide, `WEBSOCKET_CLIENT_CA_BUNDLE=/etc/ssl/certs` into `/etc/environment` (and then reboot your system).

**Comment by engn33r** [comment]
Those who commented on this issue previously seem to know more about it than I do, but it seems that the use of system certs instead of a custom certs.pem file was resolved with #88, and using system certs should be the current default. #307 added support for a custom CA bundle, in case that's relevant. I'll close this issue for now, but if I am mistaken or there are still problems, you can reopen the issue and add additional details.

**Comment by engn33r** [comment]
To add further closure, it looks like the custom CA bundle was removed shortly after the above thread in #415
