### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by Poipt** [websocket-client/websocket-client#515]
When I import the plugin, this issue comes up and the program stops:

Traceback (most recent call last):
  File "/home/runner/.site-packages/websocket/_http.py", line 143, in _get_addrinfo_list
    hostname, port, 0, 0, socket.SOL_TCP)
  File "/usr/local/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 27, in <module>
    ws.connect("[ws server]")
  File "/home/runner/.site-packages/websocket/_core.py", line 220, in connect
    options.pop('socket', None))
  File "/home/runner/.site-packages/websocket/_http.py", line 113, in connect
    hostname, port, is_secure, proxy)
  File "/home/runner/.site-packages/websocket/_http.py", line 154, in _get_addrinfo_list
    raise WebSocketAddressException(e)
websocket._exceptions.WebSocketAddressException: [Errno -2] Name or service not known

It was working perfectly yesterday, but then I got this error. I have tried reinstalling multiple times.

**Comment by Poipt** [comment]
Never mind, I was doing "ws://https://" instead of just "ws://" and that caused the issue.
