### ISSUE TITLE
When `None` is returned from `headers.get` during subprotocol validation, calling `lower` throws

### ISSUE THREAD

**Issue by alxyng** [websocket-client/websocket-client#516]
I had this issue when using setting `subprotocols` in the `WebSocketApp` constructor but no issue when the argument was omitted.

```
Traceback (most recent call last):
  File "/Users/alex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/websocket/_app.py", line 254, in run_forever
    proxy_type=proxy_type)
  File "/Users/alex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/websocket/_core.py", line 223, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/Users/alex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/websocket/_handshake.py", line 82, in handshake
    success, subproto = _validate(resp, key, options.get("subprotocols"))
  File "/Users/alex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/websocket/_handshake.py", line 180, in _validate
    subproto = headers.get("sec-websocket-protocol", None).lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by engn33r** [comment]
This should be fixed with PR #617. Please share if that is not the case.
