### ISSUE TITLE
Module cannot be imported in Python 3.4.2 due to AttributeError ("PY34")

### ISSUE THREAD

**Issue by DDR0** [websocket-client/websocket-client#521]
Hello. I have installed the websocket-client module by running `pip3 install websocket-client`, on my Debian 8 machine with Python 3.4.2 installed.

However, when I try to import the module as follows, it throws an error:
```
root@owo:~/camera# python3
Python 3.4.2 (default, Oct  8 2014, 14:47:30)
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import websockets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'websockets'
>>> import websocket
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/websocket/__init__.py", line 23, in <module>
    from ._app import WebSocketApp
  File "/usr/local/lib/python3.4/dist-packages/websocket/_app.py", line 36, in <module>
    from ._core import WebSocket, getdefaulttimeout
  File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 34, in <module>
    from ._handshake import *
  File "/usr/local/lib/python3.4/dist-packages/websocket/_handshake.py", line 40, in <module>
    if six.PY34:
AttributeError: 'module' object has no attribute 'PY34'
>>>
```

I believe this is a bug because README.rst claims, "This module is tested on Python 2.7 and Python 3.4+."

Thanks,
–DDR

**Comment by DDR0** [comment]
I downgraded to websocket-client==0.40.0, then upgraded to 0.50.0, then upgraded all the way and it worked. Very strange.

And thus, I cannot reproduce the issue now, though it certainly reproduced before.
