### ISSUE TITLE
ValueError: scheme http is invalid exception seen when websocket module used for localhost based connections

### ISSUE THREAD

**Issue by jpshivakavi** [websocket-client/websocket-client#538]
When websocket module is used for establishing websocket connection to a localhost address(127.0.0.1), it throws an exception as given below
ValueError: scheme http is invalid

Traceback (most recent call last):
  File "C:/work/tools/win_error_monitor/test.py", line 4, in <module>
    start_monitoring_errors(tc_id)
  File "C:/work/tools/win_error_monitor\win_error_monitor.py", line 178, in start_monitoring_errors
    _connect_to_error_monitoring_service()
  File "C:/work/tools/win_error_monitor\win_error_monitor.py", line 106, in _connect_to_error_monitoring_service
    _ws.connect('ws://127.0.0.1:54321/echo')
  File "C:\Python27\lib\site-packages\websocket_client-0.54.0-py2.7.egg\websocket\_core.py", line 229, in connect
    options.pop('socket', None))
  File "C:\Python27\lib\site-packages\websocket_client-0.54.0-py2.7.egg\websocket\_http.py", line 107, in connect
    hostname, port, resource, is_secure = parse_url(url)
  File "C:\Python27\lib\site-packages\websocket_client-0.54.0-py2.7.egg\websocket\_url.py", line 63, in parse_url
    raise ValueError("scheme %s is invalid" % scheme)
ValueError: scheme http is invalid
>>>

**Comment by jpshivakavi** [comment]
This issue is seen on systems which have the environment variable http_proxy  set to some proxy server address

**Comment by jpshivakavi** [comment]
I have fixed this issue and raised a pull request https://github.com/websocket-client/websocket-client/pull/539

**Comment by jpshivakavi** [comment]
Is there any timelines by when the fix for this issue will be merged with master branch

**Comment by jpshivakavi** [comment]
Will this fix be considered for merging with the master repo?

**Comment by engn33r** [comment]
PR #539 was merged over a year ago and should address this issue
