### ISSUE TITLE
websocket in a thread

### ISSUE THREAD

**Issue by LucasStinchcombe** [websocket-client/websocket-client#543]
When trying to consume from websocket in a thread using `threading` module:

``` python
import logging                                    
import websocket                                    
import json                                    
                                               
logging.basicConfig()                                                         
logging.getLogger().setLevel(logging.INFO)                                    
                                                                              
LOG = logging.getLogger(__name__)                                             
                                                                              
class WebsocketThread(threading.Thread):                                      
                                                                              
    def __init__(self):                                                       
        super(WebsocketThread, self).__init__()                               
        self.url = ("wss://some_url")                                          
                                                                              
        self.ws = websocket.WebSocketApp(                                     
            self.url,                                                         
            on_open=self.on_open,                                             
            on_close=self.on_close,                      
            on_error=self.on_error,                                  
            on_message=self.on_message)                                
                                                                       
    def on_open(self):                                                     
        LOG.info('websocket connection open')    
                                                          
    def on_message(self, msg):                                                
        LOG.info('received message: %s', msg)    
                                                                  
    def on_error(self, error):                                                
        LOG.info('websocket connection err:', error)                          
                                                                          
    def on_close(self):                                      
        LOG.info('websocket connection closed')                   
                                                                              
    def run(self):                                                        
        self.ws.run_forever() 
```

I get the following:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/websocket/_app.py", line 256, in run_forever
    dispatcher = self.create_dispatcher(ping_timeout)
  File "/usr/lib/python3.7/site-packages/websocket/_app.py", line 316, in create_dispatcher
    if self.sock.is_ssl():
AttributeError: 'NoneType' object has no attribute 'is_ssl'
```
main code looks like:
```python
from websocket_thread import WebsocketThread    
    
t = WebsocketThread()    
t.start()  
```

Interestingly enough, when running identical main code in interpreter shell, thread runs correctly with no error.

Perhaps I'm missing something.
Maybe someone can point me to some explanation.

**Comment by LucasStinchcombe** [comment]
My mistake, misunderstood the point of `thead.join()`

**Comment by ReachY** [comment]
How did you solve this problem? I also encountered this problem. @LucasStinchcombe

**Comment by LucasStinchcombe** [comment]
Haven't looked at this in a while. I remember I took a peak and found a stop condition in `websocket.WebSocketApp` called `keep_running, but I'm not so sure this is really part of interface. Anyway, I wanted to have a bunch of open connections running concurrently with graceful stop on SIGINT. So ended up with something like this:

```python
import logging                                    
import websocket                                    
import signal
import threading
                                               
logging.basicConfig()                                                         
logging.getLogger().setLevel(logging.INFO)                                    
                                                                              
LOG = logging.getLogger(__name__)             

def get_signal_handler(threads):                                                
    """ Get signal handler that stops all threads. """                          
                                                                                
    def signal_handler(signum, frame):                                          
        LOG.info("Received signal %s, stopping all threads", signum)            
        for thread in threads:                                                  
            thread.stop()                                                       
                                                                                
    return signal_handler                                      

class WebsocketThread(threading.Thread):                                      
                                                                              
    def __init__(self):                                                       
        super(WebsocketThread, self).__init__()                               
        self.url = ("wss://some_url")                                                                   
                                                                       
    def on_open(self):                                                     
        LOG.info('websocket connection open')    
                                                          
    def on_message(self, msg):                                                
        LOG.info('received message: %s', msg)    
                                                                  
    def on_error(self, error):                                                
        LOG.info('websocket connection err:', error)                          
                                                                          
    def on_close(self):                                      
        LOG.info('websocket connection closed')                   
                                                                              
    def run(self):                                                            
        self.ws = websocket.WebSocketApp(                                     
            self.url,                                                         
            on_open=self.on_open,                                             
            on_close=self.on_close,                      
            on_error=self.on_error,                                  
            on_message=self.on_message)
                              
        self.ws.run_forever() 

    def stop(self):                                                                           
        self.ws.keep_running = False

if __name__ == "__main__":
    threads = [WebsocketThread(), WebsocketThread()]

    for thread in threads:
        thread.start()
    
    signal.signal(signal.SIGINT, get_signal_handler(threads))

    for thread in threads:
        thread.join()
```

FYI I haven't tested this but hopefully that's of use to you.
