### ISSUE TITLE
NoneType __getitem__ @ _abnf.py extract()

### ISSUE THREAD

**Issue by andresriancho** [websocket-client/websocket-client#548]
```console
$ pip list | grep websocket
websocket-client                   0.56.0
```

```python
Exception in thread DebugChromeInterface:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/eth/tools/w3af/w3af/core/controllers/chrome/devtools/main.py", line 295, in run
    data = self.recv()
  File "/home/eth/tools/w3af/w3af/core/controllers/chrome/devtools/main.py", line 239, in recv
    data = self.ws.recv()
  File "/home/eth/tools/virtualenvs/w3af/local/lib/python2.7/site-packages/websocket/_core.py", line 313, in recv
    opcode, data = self.recv_data()
  File "/home/eth/tools/virtualenvs/w3af/local/lib/python2.7/site-packages/websocket/_core.py", line 330, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/eth/tools/virtualenvs/w3af/local/lib/python2.7/site-packages/websocket/_core.py", line 354, in recv_data_frame
    return self.cont_frame.extract(frame)
  File "/home/eth/tools/virtualenvs/w3af/local/lib/python2.7/site-packages/websocket/_abnf.py", line 442, in extract
    frame.data = data[1]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by engn33r** [comment]
While this may be a legitimate issue in the code, I cannot provide much feedback based on the error trace shared above. It would help a lot if you could provide some more info, such as the details mentioned in [the contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md#i-got-an-error-or-i-have-a-question). The best information that would show the exact problem is an example WebSocket frame that triggers this error, if you are able to use Wireshark to capture it. If this issue still occurs in the latest 0.58.0 release and with Python 3, I certainly want to fix this issue. I will close this issue for now until more info is provided using the latest 0.58.0 release.
