### ISSUE TITLE
Python script stops after connection loss

### ISSUE THREAD

**Issue by AlexGooi** [websocket-client/websocket-client#551]
Hello, 

 I'm relative new to python.
I'm trying to make an script that is reading data from a infrared camera. 
The data is received via web sockets.
I Used the following code:
`
from websocket import create_connection

#Create connection to websocket 
#-------------------------------------------------------------------------------------

while (1): 
        ws = create_connection("ws://192.168.2.254:81")
#Receive camera data
        string =  ws.recv()
        print (string)
        ws.close()
` 
This runs fine, but when the camera is disconnected and reconnected again I get the following error, and the script stops:
 Traceback (most recent call last):
  File "testws.py", line 8, in <module>
    ws = create_connection("ws://192.168.2.254:81")
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 226, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/local/lib/python3.7/site-packages/websocket/_handshake.py", line 79, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/lib/python3.7/site-packages/websocket/_handshake.py", line 158, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/usr/local/lib/python3.7/site-packages/websocket/_http.py", line 305, in read_headers
    line = recv_line(sock)
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 123, in recv_line
    c = recv(sock, 1)
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 102, in recv
    bytes_ = _recv()
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 84, in _recv
    return sock.recv(bufsize)
ConnectionResetError: [Errno 104] Connection reset by peer

Is there a way to detect if the connection is lost, and automatically reconnect when the camera is back up, without the script stopping?

Thanks in advance.

**Comment by AlexGooi** [comment]
Already fixed the issue:
I made use of an try statement and now it works.
`
while (1): 
        try:
                ws = create_connection("ws://192.168.2.254:81")
                ws.settimeout(5)
                print("Connected")
                print(ws.gettimeout())
                string = ws.recv()
                try:
                        string = ws.recv()
                        print(string)
                except:
                        print("Can't receive data")
                ws.close()
        except:
                print("Can't create connection")
`
