### ISSUE TITLE
Calling disconnect sometimes results in exception that cant be trapped

### ISSUE THREAD

**Issue by VeNoMouS** [websocket-client/websocket-client#619]
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/engineio/client.py", line 689, in _write_loop
    self.ws.send(encoded_packet)
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 242, in send
    return self.send_frame(frame)
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 267, in send_frame
    l = self._send(data)
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 437, in _send
    return send(self.sock, data)
  File "/usr/lib/python3/dist-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
OSError: [Errno 9] Bad file descriptor
```

or

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/engineio/client.py", line 689, in _write_loop
    self.ws.send(encoded_packet)
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 242, in send
    return self.send_frame(frame)
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 267, in send_frame
    l = self._send(data)
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 437, in _send
    return send(self.sock, data)
  File "/usr/lib/python3/dist-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by VeNoMouS** [comment]
Sorry ... this is with latest stable package.

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/engineio/client.py", line 689, in _write_loop
    self.ws.send(encoded_packet)
  File "/usr/local/lib/python3.7/dist-packages/websocket/_core.py", line 253, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.7/dist-packages/websocket/_core.py", line 279, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.7/dist-packages/websocket/_core.py", line 449, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.7/dist-packages/websocket/_socket.py", line 157, in send
    return _send()
  File "/usr/local/lib/python3.7/dist-packages/websocket/_socket.py", line 139, in _send
    return sock.send(data)
OSError: [Errno 9] Bad file descriptor

```

**Comment by engn33r** [comment]
It looks like the root issue may not be websocket-client but rather the [python-engineio library](https://github.com/miguelgrinberg/python-engineio). This is indicated by the line `File "/usr/local/lib/python3.7/dist-packages/engineio/client.py", line 689, in _write_loop`. I would suggest checking in with that project's team, or it is possible that they may already have fixed this issue. On a related topic, if your custom code is dealing with threads, as the error message indicates, you can review the [project documentation about threading](https://websocket-client.readthedocs.io/en/latest/threading.html).
