### ISSUE TITLE
run_forever in python 3.9

### ISSUE THREAD

**Issue by pabloapdz** [websocket-client/websocket-client#641]
Python 3.9 changed some codes, and "isAlive" don't exists more in threading.. Now is "Is_Alive" and another things..

```
'Thread' object has no attribute 'isAlive'Exception in thread Thread-331:
Traceback (most recent call last):
  File "C:\python39\lib\site-packages\websocket\_app.py", line 306, in run_forever

    dispatcher.read(self.sock.sock, read, check)
  File "C:\python39\lib\site-packages\websocket\_app.py", line 66, in read
    if not read_callback():
  File "C:\python39\lib\site-packages\websocket\_app.py", line 270, in read
    return teardown()
  File "C:\python39\lib\site-packages\websocket\_app.py", line 231, in teardown
    if thread and thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'
```

**Comment by tirkarthi** [comment]
PR : https://github.com/websocket-client/websocket-client/pull/594

**Comment by engn33r** [comment]
PR #594 has been merged, so this should be resolved
