### ISSUE TITLE
testConnect (websocket.tests.test_http.HttpTest) should probably belong to the 'Internet-requiring tests' category

### ISSUE THREAD

**Issue by mgorny** [websocket-client/websocket-client#685]
I suppose the test needs Internet access:

```
======================================================================
ERROR: testConnect (websocket.tests.test_http.HttpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/portage/dev-python/websocket-client-0.59.0/work/websocket-client-0.59.0/websocket/tests/test_http.py", line 96, in testConnect
    self.assertRaises(TypeError, _open_proxied_socket, "wss://example.com", OptsList(), proxy_info(http_proxy_host="example.com", http_proxy_port="8080", proxy_type="http"))
  File "/usr/lib/pypy3.7/lib-python/3/unittest/case.py", line 756, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib/pypy3.7/lib-python/3/unittest/case.py", line 178, in handle
    callable_obj(*args, **kwargs)
  File "/tmp/portage/dev-python/websocket-client-0.59.0/work/websocket-client-0.59.0/websocket/_http.py", line 92, in _open_proxied_socket
    socket_options=DEFAULT_SOCKET_OPTION + options.sockopt
  File "/usr/lib/pypy3.7/site-packages/socks.py", line 180, in create_connection
    for r in socket.getaddrinfo(proxy_addr, proxy_port, 0, socket.SOCK_STREAM):
  File "/usr/lib/pypy3.7/lib-python/3/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
_socket.gaierror: [Errno -2] Name or service not known
```

**Comment by engn33r** [comment]
Thanks, good catch. I added this unittest to the TEST_WITH_INTERNET category, as you suggested, because it does perform a DNS lookup. An offline test was added to CI to catch this type of issue going forward.

**Comment by mgorny** [comment]
Thank you!
