### ISSUE TITLE
SSLEOF Error

### ISSUE THREAD

**Issue by savage-eagle** [websocket-client/websocket-client#692]
Hi, sometimes this errors is happening when sending data via websocket.

```
[12-05-2021 11:18:48.708] - Traceback (most recent call last):
  File "api.py", line 320, in send_request
    self.websocket.send(data)
  File "C:\Program Files\Python39\lib\site-packages\websocket\_app.py", line 182, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "C:\Program Files\Python39\lib\site-packages\websocket\_core.py", line 283, in send
    return self.send_frame(frame)
  File "C:\Program Files\Python39\lib\site-packages\websocket\_core.py", line 311, in send_frame
    l = self._send(data)
  File "C:\Program Files\Python39\lib\site-packages\websocket\_core.py", line 512, in _send
    return send(self.sock, data)
  File "C:\Program Files\Python39\lib\site-packages\websocket\_socket.py", line 167, in send
    return _send()
  File "C:\Program Files\Python39\lib\site-packages\websocket\_socket.py", line 149, in _send
    return sock.send(data)
  File "C:\Program Files\Python39\lib\ssl.py", line 1173, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2472)
```

I'm creating the websocket with thoses parameters
```
self.websocket_thread = threading.Thread(
	target=self.websocket.run_forever,
	kwargs={
		"sslopt": {"check_hostname": False, "cert_reqs": ssl.CERT_NONE,},
		"skip_utf8_validation": True,
		"http_proxy_host": None,
		"http_proxy_port": None,
		"http_proxy_auth": None,
	},
)
```

Versions been used:
websocket-client 0.59.0
pyopenssl not installed
pyasn1 0.4.8
ndg-httpsclient 0.5.1
Python 3.9.1

**Comment by engn33r** [comment]
I have some questions to try and recreate this issue:
1. Does this always happen when you run your code, or does it not happen consistently?
2. What version of [Python ssl](https://pypi.org/project/ssl/) do you have installed? Try using `python -c "import ssl; print(ssl.OPENSSL_VERSION)"`
3. Which version of Windows are you using?
4. Can you provide a complete [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), ideally referencing a public websocket endpoint, to demonstrate how to recreate this issue?
5. Have you reviewed the [project's threading documentation](https://websocket-client.readthedocs.io/en/latest/threading.html) for ideas, or checked if this issue occurs without threads?

I tried the following code, mostly borrowed from [the examples page](https://websocket-client.readthedocs.io/en/latest/examples.html), and while it does not use threads, I and did encounter any issues. I am using Python 3.9.2 and OpenSSL 1.1.1i on Windows 10.
```python
import websocket
import threading
import ssl

def on_message(wsapp, message):
    print(message)

wsapp = websocket.WebSocketApp("wss://stream.meetup.com/2/rsvps", on_message=on_message)
wsapp.run_forever(sslopt={"check_hostname": False, "cert_reqs": ssl.CERT_NONE}, skip_utf8_validation=True)
```

**Comment by engn33r** [comment]
Closing due to lack of activity, but if an update is received I can reopen this issue.

**Comment by klarose** [comment]
I also see this issue. Same behaviour. Python 3.10 on Linux. The problem seems to go away if I make send/receive mutually exclusive, which isn't a good solution. I do have the multithreading flag set to true in the websocket. I also set 
`sslopt["suppress_ragged_eofs"] = False` so that I received the EOF exception rather than it just returning that the connection closed as a way of distinguishing between a legitimate remote teardown of the socket and this case.

Of note: somewhere else in the process I am running Tornado via a library I have not written. Data does make its way to/from that eventloop. It's possible that comes into play. That said, the eventloop is just another thread at its core, right? So, at worst it should just block unnecessarily. It certainly shouldn't cause corruption of the tls layer of the socket it is reading/writing. You may ask why I'm not using an asyncio websocket library: the reason is that the code in question used to deal with a non-async tcp socket. I have simply replaced that 'transport' with a websocket tunnel, essentially.

I have a packet capture which shows that the tcp socket had no data received within 500ms of the failure. So, I don't think it's the far end actually responding with bad data. It definitely looks like some sort of local corruption.
