### ISSUE TITLE
Can not connect to the server by WebSocketAPP when using Shadowsocks

### ISSUE THREAD

**Issue by MixianLiu** [websocket-client/websocket-client#696]
Hi everyone,
    I have to use Shadowsocks to get access to some blocked websites and servers. However when I try to use WebSocketAPP to connect the address that been block, the program always returns to [WinError 10060]. I'm sure the shadowsocks works well and on the global mode, and I can connect to this address by some online test website(https://www.piesocket.com/websocket-tester#). I also can connect to other not blocked address when turning off shadowsocks.

```python
import websocket
try:
    import thread
except ImportError:
    import _thread as thread
import time

def on_message(ws, message):
    print(message)

def on_error(ws, error):
    print(error)

def on_close(ws):
    print("### closed ###")

def on_open(ws):
    def run(*args):
        for i in range(3):
            time.sleep(1)
            ws.send("Hello %d" % i)
        time.sleep(1)
        ws.close()
        print("thread terminating...")
    thread.start_new_thread(run, ())

if __name__ == "__main__":
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp("wss://stream.binance.com:9443/ws/!ticker@arr",
                              on_open = on_open,
                              on_message = on_message,
                              on_error = on_error,
                              on_close = on_close)

    ws.run_forever()
```

**Comment by engn33r** [comment]
You are correct, there are some problems using proxies. Can you share the full error message you receive when you try to connect using shadowsocks? I want to check if it is the same error I am seeing. And if possible, can you use the updated master with commit 7a70aef?

I am using the following code to run a test:
```python
import websocket
import ssl

websocket.enableTrace(True)

ws = websocket.WebSocket(sslopt={"cert_reqs": ssl.CERT_NONE})
ws.connect("wss://stream.binance.com:9443/ws/!ticker@arr",
  http_proxy_host="127.0.0.1", http_proxy_port="1080", proxy_type="socks5")
ws.send("Hello Server")
print(ws.recv())
ws.close()
```

I receive this error:
```
Traceback (most recent call last):
  File "wstest.py", line 8, in <module>
    ws.connect("wss://stream.binance.com:9443/ws/!ticker@arr",
  File "/usr/local/lib/python3.8/dist-packages/websocket_client-1.0.1-py3.8.egg/websocket/_core.py", line 255, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/usr/local/lib/python3.8/dist-packages/websocket_client-1.0.1-py3.8.egg/websocket/_http.py", line 106, in connect
    return _open_proxied_socket(url, options, proxy)
  File "/usr/local/lib/python3.8/dist-packages/websocket_client-1.0.1-py3.8.egg/websocket/_http.py", line 91, in _open_proxied_socket
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/usr/local/lib/python3.8/dist-packages/websocket_client-1.0.1-py3.8.egg/websocket/_http.py", line 259, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/usr/local/lib/python3.8/dist-packages/websocket_client-1.0.1-py3.8.egg/websocket/_http.py", line 237, in _wrap_sni_socket
    return context.wrap_socket(
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
```

So I changed the sslopt to include `"do_handshake_on_connect": False`, as seen in the revised code below:
```python
import websocket
import ssl

websocket.enableTrace(True)

ws = websocket.WebSocket(sslopt={"cert_reqs": ssl.CERT_NONE, "do_handshake_on_connect": False})
ws.connect("wss://stream.binance.com:9443/ws/!ticker@arr",
  http_proxy_host="127.0.0.1", http_proxy_port="1080", proxy_type="socks5")
ws.send("Hello Server")
print(ws.recv())
ws.close()
```

And then I get this error:
```
Traceback (most recent call last):
  File "wstest.py", line 8, in <module>
    ws.connect("wss://stream.binance.com:9443/ws/!ticker@arr",
  File "/usr/local/lib/python3.8/dist-packages/websocket_client-1.0.1-py3.8.egg/websocket/_core.py", line 259, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/local/lib/python3.8/dist-packages/websocket_client-1.0.1-py3.8.egg/websocket/_handshake.py", line 56, in handshake
    send(sock, header_str)
  File "/usr/local/lib/python3.8/dist-packages/websocket_client-1.0.1-py3.8.egg/websocket/_socket.py", line 175, in send
    return _send()
  File "/usr/local/lib/python3.8/dist-packages/websocket_client-1.0.1-py3.8.egg/websocket/_socket.py", line 152, in _send
    return sock.send(data)
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
OSError: [Errno 0] Error
```

If you confirm that these are the same errors you are seeing, I can dive deeper to try to fix the issue here. I think the problems may exist using websocket-client with any SOCKS proxy.

**Comment by engn33r** [comment]
Closing due to inactivity and lack of detailed information for troubleshooting.

While I do not disagree that there are possibly issues with the SOCKS4/SOCKS5 proxy support, I don't think the issue is specific to shadowsocks. The PySocks project that this library uses was last updated in 2019, so the main takeaways here are:
1. This library should eventually migrate to supporting proxies with maintained code. If you can suggest an alternative library that could replace PySocks, please share!
2. Right now the Github Action CI tests do not cover the websocket-client proxy code, which should also be remedied.
