### ISSUE TITLE
'NoneType' object has no attribute 'is_ssl'

### ISSUE THREAD

**Issue by IceflowRE** [websocket-client/websocket-client#720]
Client connects and disconnect sucessful to the server.

```
websocket-client 1.1.0
Python 3.9.6
Windows 10 21H1
```

code:
```python
def runner(ws):
    ws.run_forever()


if __name__ == '__main__':
    ws = WebSocketApp(
        f"ws://localhost:34842/api/1.0.0",
        on_error=on_error,
    )
    ws_executor = Thread(target=runner, args=(ws,))
    ws_executor.start()
    time.sleep(1)
    ws.close()
    ws_executor.join()
```

output:
```
on_error: 'NoneType' object has no attribute 'is_ssl'
```

traceback:
```
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\websocket\_app.py", line 320, in run_forever
    dispatcher = self.create_dispatcher(ping_timeout)
  File "C:\Python39\lib\site-packages\websocket\_app.py", line 380, in create_dispatcher
    if self.sock.is_ssl():
AttributeError: 'NoneType' object has no attribute 'is_ssl'
```

Might be related to #711 .

**Comment by engn33r** [comment]
Yes, this might be related to 711. Can you test if the current master branch with the latest commit fixed the issue?

**Comment by engn33r** [comment]
Closing due to lack of follow-up

**Comment by nicholas-cryptowatch** [comment]
Still seeing this in 1.2.1. Will try to implement a fix when I have time.

**Comment by engn33r** [comment]
@nicholas-cryptowatch you might try specifying a dispatcher as a parameter in `run_forever()`, which skips the `dispatcher = self.create_dispatcher(ping_timeout)` line entirely. I updated the README to include an example of that and the docs now mention this option: https://websocket-client.readthedocs.io/en/latest/examples.html#dispatching-multiple-websocketapps

Are you encountering this issue on Windows? Code coverage is reaching these lines of _app.py but runs on Ubuntu, so it's possible Windows acts differently.

**Comment by rrfaria** [comment]
How you solved it ? 
I have same error here, after a long period running, in a random time this error appears:

```
'NoneType' object has no attribute 'is_ssl'
```

and I'm using [v1.3.2](https://github.com/websocket-client/websocket-client/releases/tag/v1.3.2)
python 3.7.11

**Comment by IceflowRE** [comment]
As of 1.3.2 the initial problem does not appear anymore.

**Comment by paco-bazan** [comment]
Hello, I am facing a similar issue using version 1.3.3, please see below the traceback:
`Exception in thread Thread-13:
Traceback (most recent call last):
  File "/Users/curr0/.pyenv/versions/3.9.13/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Users/curr0/.pyenv/versions/3.9.13/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/curr0/.pyenv/versions/3.9.13/envs/maximaor2/lib/python3.9/site-packages/pybit/_websocket_stream.py", line 143, in <lambda>
    self.wst = threading.Thread(target=lambda: self.ws.run_forever(
  File "/Users/curr0/.pyenv/versions/3.9.13/envs/maximaor2/lib/python3.9/site-packages/websocket/_app.py", line 386, in run_forever
    self._callback(self.on_error, e)
  File "/Users/curr0/.pyenv/versions/3.9.13/envs/maximaor2/lib/python3.9/site-packages/websocket/_app.py", line 429, in _callback
    self.on_error(self, e)
  File "/Users/curr0/.pyenv/versions/3.9.13/envs/maximaor2/lib/python3.9/site-packages/pybit/_websocket_stream.py", line 139, in <lambda>
    on_error=lambda ws, err: self._on_error(err)
  File "/Users/curr0/.pyenv/versions/3.9.13/envs/maximaor2/lib/python3.9/site-packages/pybit/_websocket_stream.py", line 205, in _on_error
    raise error
  File "/Users/curr0/.pyenv/versions/3.9.13/envs/maximaor2/lib/python3.9/site-packages/websocket/_app.py", line 424, in _callback
    callback(self, *args)
  File "/Users/curr0/.pyenv/versions/3.9.13/envs/maximaor2/lib/python3.9/site-packages/pybit/_websocket_stream.py", line 139, in <lambda>
    on_error=lambda ws, err: self._on_error(err)
  File "/Users/curr0/.pyenv/versions/3.9.13/envs/maximaor2/lib/python3.9/site-packages/pybit/_websocket_stream.py", line 205, in _on_error
    raise error
  File "/Users/curr0/.pyenv/versions/3.9.13/envs/maximaor2/lib/python3.9/site-packages/websocket/_app.py", line 334, in run_forever
    dispatcher = self.create_dispatcher(ping_timeout, dispatcher)
  File "/Users/curr0/.pyenv/versions/3.9.13/envs/maximaor2/lib/python3.9/site-packages/websocket/_app.py", line 397, in create_dispatcher
    if self.sock.is_ssl():`

**Comment by paco-bazan** [comment]
Just updated to the latest version 1.5.1, will update in case it happens again
