### ISSUE TITLE
Encountering "The write operation timed out" exception + SSL errors

### ISSUE THREAD

**Issue by aknooh** [websocket-client/websocket-client#725]
While doing an upload test to a server using websockets, the program is encountering `The write operation timed out` exception and `SSL: BAD_LENGTH] unknown error`  and `SSL unknown error` errors. This is similar to #591, but the issues persist even after enabling `multi-threading` flag. Here's a simpler version of the program: [simple_websocket_connection.py](https://gist.github.com/aknooh/78162cd2676639dca59dd357758815f5)
The program does not use threads, but use multiprocessing. It spawns multiple processes that open a few websocket connections to a particular server and send and receive data. 

Here are the tracebacks encountered when running the program:

```
2021-07-30 23:11:01,485 - AGENT - DEBUG - WebSocketTimeoutException in uplink sending data: The write operation timed outTraceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/websocket/_socket.py", line 175, in send
  File "/usr/lib/python3.8/site-packages/websocket/_socket.py", line 152, in _send
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/myLib/client.py", line 435, in send_data
    websocket_conn.send(self.data, opcode=websocket.ABNF.OPCODE_BINARY)
  File "/usr/lib/python3.8/site-packages/websocket/_core.py", line 282, in send
  File "/usr/lib/python3.8/site-packages/websocket/_core.py", line 310, in send_frame
  File "/usr/lib/python3.8/site-packages/websocket/_core.py", line 514, in _send
  File "/usr/lib/python3.8/site-packages/websocket/_socket.py", line 178, in send
websocket._exceptions.WebSocketTimeoutException: The write operation timed out

2021-07-30 23:11:01,488 - AGENT - DEBUG - uplink websocket_conn.recv() : exception [SSL: BAD_LENGTH] unknown error (_ssl.c:2472)
Traceback (most recent call last):
  File "/usr/lib/myLib/client.py", line 544, in client_to_server_test
    last_server_response = websocket_conn.recv()
  File "/usr/lib/python3.8/site-packages/websocket/_core.py", line 353, in recv
  File "/usr/lib/python3.8/site-packages/websocket/_core.py", line 376, in recv_data
  File "/usr/lib/python3.8/site-packages/websocket/_core.py", line 416, in recv_data_frame
  File "/usr/lib/python3.8/site-packages/websocket/_core.py", line 342, in pong
  File "/usr/lib/python3.8/site-packages/websocket/_core.py", line 282, in send
  File "/usr/lib/python3.8/site-packages/websocket/_core.py", line 310, in send_frame
  File "/usr/lib/python3.8/site-packages/websocket/_core.py", line 514, in _send
  File "/usr/lib/python3.8/site-packages/websocket/_socket.py", line 175, in send
  File "/usr/lib/python3.8/site-packages/websocket/_socket.py", line 152, in _send
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
ssl.SSLError: [SSL: BAD_LENGTH] unknown error (_ssl.c:2472)

2021-07-30 23:11:01,491 - AGENT - DEBUG - start the test with 4 process
2021-07-30 23:11:01,493 - AGENT - DEBUG - - start download & upload test# 2
2021-07-30 23:11:01,496 - AGENT - DEBUG -  on_error: timed out
2021-07-30 23:11:01,499 - AGENT - DEBUG -  WebSocketTimeoutException in uplink sending data: The write operation timed outTraceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/websocket/_socket.py", line 175, in send
  File "/usr/lib/python3.8/site-packages/websocket/_socket.py", line 152, in _send
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/myLib/client.py", line 435, in send_data
    websocket_conn.send(self.data, opcode=websocket.ABNF.OPCODE_BINARY)
  File "/usr/lib/python3.8/site-packages/websocket/_core.py", line 282, in send
  File "/usr/lib/python3.8/site-packages/websocket/_core.py", line 310, in send_frame
  File "/usr/lib/python3.8/site-packages/websocket/_core.py", line 514, in _send
  File "/usr/lib/python3.8/site-packages/websocket/_socket.py", line 178, in send
websocket._exceptions.WebSocketTimeoutException: The write operation timed out

2021-07-30 23:11:01,502 - AGENT - DEBUG -  uplink websocket_conn.recv() : exception The write operation timed out
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/websocket/_socket.py", line 175, in send
  File "/usr/lib/python3.8/site-packages/websocket/_socket.py", line 152, in _send
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
socket.timeout: The write operation timed out
```

**Comment by engn33r** [comment]
Do you get this error immediately at the start of running the simple_websocket_connection.py code you shared in the gist? When I try running that code, I see 8 "open handler" messages, some messages being sent and received, and everything seems to end cleanly. So if this is not the result you are seeing, can you share some info about the system you are using:
1. What version of Python?
2. What version of websocket-client?
3. What version of OpenSSL?
4. What OS are you using?

**Comment by aknooh** [comment]
`simple_websocket_connection.py` is a simplified version of the main program that's running on an embedded linux device. This shared code in gist may not reproduce the problem.
Answers:
1. Python3.8.5
2. websocket-client-v1.1.0
3. CiscoSSL 1.0.2n.6.2.194-fips - propriety. Used in 100s of products. Fully tested.
4. Embedded Linux - Based on 3.14.x kernel

**Comment by engn33r** [comment]
Ok, it's useful that you shared some example code but it would make it easier for me to troubleshoot the exact issue if you shared code that can recreate the issue. With the information provided, I can't be sure what the exact problem is, but I can share some ideas.
1. I see there are many socket.timeout messages. Past issues in this project have shown that websocket-client can work with over a thousand parallel connections, so I wonder if the server or the network could be part of the issue. Are you using a widely used websocket server that can handle many connections at once? Can you check the server logs to determine whether it is handling these client connections properly? If the server is not under your control (for example, it is a public URL owned by a third party), try testing with a local server to verify the issue is not on the server side. If you want to check what is happening with the network, capture the network traffic with wireshark (on the client, or the server, or both) to understand whether the packets are leaving the host and arriving at the server.
2. Try setting `websocket.enableTrace(True)` for debugging to determine what messages are sent and received. This might help you see more clearly what is happening in the connection process. This will also enable the callback exception code that is currently being discussed in issue #377.
3. I see a line with an SSL error, `ssl.SSLError: [SSL: BAD_LENGTH] unknown error (_ssl.c:2472)`. If you search for "_ssl.c" in old issues of this project, you will find many instances where SSL was the problem. Sometimes using an older version of OpenSSL causes this error, possibly because the SSL library on the server does not interface well with the SSL library on the client. It looks like you are using a slightly less common SSL library, so SSL compatibility between client and server (and proxy, if a proxy is involved) might be worth checking.
4. If you are running a large number of parallel connections, could you be encountering limitations of the embedded device you are using? If you cannot recreate the same issue on a standard computer on the same network, the issue might a limitation of your embedded environment (libraries, networking, memory, etc.). In Linux, when using over 1024 sockets, you want to set `ulimit -n` to resolve the issue outlined in #607.

**Comment by aknooh** [comment]
Closing the issue. `websocket-client` is not the root cause of these SSL trackbacks. The intermediary switches, in which this device is connected to, are the root cause of the issue. These switches would drop a few packets, and in some cases drop all packets. The websocket connection would continue listening and waiting for packets, until after some time, then it would timeout and hence the tracebacks. This was happening on the SSL module level, and the `websocket-client` does not handle this particular traceback.
In particular, the switch would drop only upstream packets (i.e. upload test, packets going from device to the server), and would not interfere with downstream (download test, packets from server to device). Anyways, closing this issue. If someone runs into similar tracebacks, make sure you have a stable websocket connection with whatever server you're trying to talk to.

**Comment by engn33r** [comment]
Thank you for sharing the solution you found!
