### ISSUE TITLE
Python Socks is needed for SOCKS proxying but is not available

### ISSUE THREAD

**Issue by yimtcode** [websocket-client/websocket-client#817]
Reference:
https://websocket-client.readthedocs.io/en/latest/examples.html?highlight=proxy#connecting-through-a-proxy

```python
import websocket

if __name__ == '__main__':
    ws = websocket.WebSocket()
    # socks5 is local
    ws.connect("ws://echo.websocket.events",
               http_proxy_host="192.168.2.81", http_proxy_port="2222", proxy_type="socks5")
    ws.send("Hello, Server")
    print(ws.recv())
    ws.close()
```

Output

```
Traceback (most recent call last):
  File "/Users/yimt/Code/PycharmProjects/hello-python/main.py", line 5, in <module>
    ws.connect("ws://echo.websocket.events",
  File "/Users/yimt/Code/PycharmProjects/hello-python/hello-python/lib/python3.10/site-packages/websocket/_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/Users/yimt/Code/PycharmProjects/hello-python/hello-python/lib/python3.10/site-packages/websocket/_http.py", line 115, in connect
    return _start_proxied_socket(url, options, proxy)
  File "/Users/yimt/Code/PycharmProjects/hello-python/hello-python/lib/python3.10/site-packages/websocket/_http.py", line 74, in _start_proxied_socket
    raise WebSocketException("Python Socks is needed for SOCKS proxying but is not available")
websocket._exceptions.WebSocketException: Python Socks is needed for SOCKS proxying but is not available
```

Example cannot be run?

**Comment by engn33r** [comment]
Follow the [installation instructions.](https://github.com/websocket-client/websocket-client#installation)
```
To install python-socks for proxy usage and wsaccel for a minor performance boost, use: pip3 install websocket-client[optional]
```
