### ISSUE TITLE
rel.dispatch() TypeError: read() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by MyPetline** [websocket-client/websocket-client#832]
Hi. I'm trying to run the code

    ws.run_forever(dispatcher=rel)  # Set dispatcher to automatic reconnection
    rel.signal(2, rel.abort)  # Keyboard Interrupt
    rel.dispatch()

The line  rel.dispatch() returns an error - TypeError: read() takes 0 positional arguments but 1 was given
Can you help me find a solution?

**Comment by MyPetline** [comment]
> Can you copy and paste the entire error message from your terminal? This will help me understand the issue better

--- request header ---
GET /v1/marketdata/BTCUSD HTTP/1.1

Upgrade: websocket

Host: api.gemini.com

Origin: http://api.gemini.com

Sec-WebSocket-Key: bXPwBmRN5zofy0vwGW5kuA==

Sec-WebSocket-Version: 13

Connection: Upgrade




-----------------------
--- response header ---
HTTP/1.1 101 Switching Protocols
Date: Fri, 24 Jun 2022 08:54:56 GMT
Connection: upgrade
Server: nginx
upgrade: websocket
sec-websocket-accept: Pr3ZBM/Atfmb9B3xC/cuJJJxSwc=
-----------------------
Opened connection
Traceback (most recent call last):
  File "C:\Python\GRID_BOT\test3.py", line 28, in <module>
    rel.dispatch()
  File "C:\Users\Kitchen PC\AppData\Local\Programs\Python\Python39\lib\site-packages\rel\rel.py", line 205, in dispatch
    registrar.dispatch()
  File "C:\Users\Kitchen PC\AppData\Local\Programs\Python\Python39\lib\site-packages\rel\registrar.py", line 72, in dispatch
    if not self.loop():
  File "C:\Users\Kitchen PC\AppData\Local\Programs\Python\Python39\lib\site-packages\rel\registrar.py", line 81, in loop
    e = self.check_events()
  File "C:\Users\Kitchen PC\AppData\Local\Programs\Python\Python39\lib\site-packages\rel\registrar.py", line 195, in check_events
    self.callback('read', fd)
  File "C:\Users\Kitchen PC\AppData\Local\Programs\Python\Python39\lib\site-packages\rel\registrar.py", line 125, in callback
    self.events[etype][fd].callback()
  File "C:\Users\Kitchen PC\AppData\Local\Programs\Python\Python39\lib\site-packages\rel\listener.py", line 108, in callback
    if not self.cb(*self.args) and not self.persist and self.active:
TypeError: read() takes 0 positional arguments but 1 was given
[Finished in 1.4s]

**Comment by engn33r** [comment]
I don't get any errors when testing this example code. Make sure you have the latest websocket-client and rel releases using `pip3 install websocket-client rel`.
