### ISSUE TITLE
Segmentation fault on recv_data_frame

### ISSUE THREAD

**Issue by JTourteau** [websocket-client/websocket-client#903]
I'm using the websocket-client module v1.5.1, python v3.10.10 and jemalloc v5.1.0 to receive data from a websocket API.

The websocket is created as follow : 

```
ws = websocket.WebSocket()
ws.connect(self.websocket_url)

self.__receive_thread = StoppableThread(name="websocket_callback", target=self.__websocket_callback)
self.__receive_thread.start()
```

The websocket protocol uses a heartbeat mechanism to detect stale connection. If a heartbeat message is not received during 30 sec, the program tries to reconnect the websocket. This is handled by a threading Timer which is reset anytime a heartbeat message is received.

```
self.reconnect_timer = threading.Timer(self.__heartbeat_timeout, self.__reconnect_timer, [ws])
self.reconnect_timer.start()
```

The `__reconnect_timer` function simply logs the reconnection timer triggering and tries to reconnect the websocket, if the reconnection fails, it cleans up the associated data.

```
def __reconnect_timer(self, websocket):
    log(f"[RECONNECT-TIMER] Timer triggered on {websocket}")
    try:
        websocket.connect()
    except:
        log(f"[RECONNECT] Reconnection failed.")
        # Cleanup here
```

The reception thread then waits for a message to be available on the websocket to treat it

```
while not self.__receive_thread.is_stopped():
    _websockets,_,_ = select.select(websockets, [], [], 0.1)
    for ws in _websockets:
        try:
            op_code, frame = ws.recv_data_frame()
        except websocket._exceptions.WebSocketConnectionClosedException:
            self.__on_close(ws)
            continue
        except Exception as e:
            log(f"Exception occured in thread __websocket_callback on {ws}: {e}")
            log(format_traceback(e.__traceback__))
            continue

        if op_code == op_codes.OPCODE_CLOSE:
            self.__ws_log(f"Close frame", f"RECEIVE - {ws}")
            self.__on_close(ws)
        elif op_code == op_codes.OPCODE_PING:
            self.__ws_log(f"Ping frame : Not supported yet", f"RECEIVE - {ws}")
        elif op_code == op_codes.OPCODE_PONG:
            self.__ws_log(f"Pong frame : Not supported yet", f"RECEIVE - {ws}")
        elif op_code == op_codes.OPCODE_CONT:
            self.__ws_log(f"Continuation frame : Not supported yet", f"RECEIVE - {ws}")
        elif op_code == op_codes.OPCODE_BINARY:
            self.__ws_log(f"Binary frame : Not supported yet", f"RECEIVE - {ws}")
        else:
            
            data = json.loads(frame.data.decode("utf-8"))

            method = data["method"]
            if method == "heartbeat":
                self.reconnect_timer.cancel()
                self.reconnect_timer = threading.Timer(self.__heartbeat_timeout, self.__reconnect_timer, [ws])
                self.reconnect_timer.start()
            else:
                # Treat data here
```

This mechanism works most of the time, however I sometime face an SIGSEGV issue that I've debugged with gdb and gives the following backtrace

```
$ gdb python_installs/python-3.10.10-debug/bin/python3.10d 1681741771_python3.10d_77179.coredump
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python_installs/python-3.10.10-debug/bin/python3.10d...

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/debian/python_installs/python-3.10.10-debug/bin/python3.10d -u /home/debi'.
Program terminated with signal SIGSEGV, Segmentation fault.
(gdb) bt
#0  atomic_load_p (mo=atomic_memory_order_relaxed, a=0xdb798) at include/jemalloc/internal/atomic_gcc_atomic.h:31
#1  rtree_leaf_elm_bits_read (dependent=true, elm=0xdb798, rtree=<optimized out>, tsdn=<optimized out>) at include/jemalloc/internal/rtree.h:175
#2  rtree_szind_slab_read (r_slab=<synthetic pointer>, r_szind=<synthetic pointer>, dependent=true, key=17628158308314461495, rtree_ctx=0x7f0269ffdf28, rtree=<optimized out>, tsdn=<optimized out>) at include/jemalloc/internal/rtree.h:464
#3  ifree (slow_path=false, tcache=0x7f0269ffe0c0, ptr=0xf4a3cc955b6f3537, tsd=<optimized out>) at src/jemalloc.c:2206
#4  free (ptr=0xf4a3cc955b6f3537) at src/jemalloc.c:2393
#5  0x00007f027a4a2b80 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#6  0x00007f027a4b0c80 in EVP_CIPHER_CTX_reset () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#7  0x00007f027a4b0d29 in EVP_CIPHER_CTX_free () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#8  0x00007f0276fcca65 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#9  0x00007f0276fce3d9 in SSL_free () from /lib/x86_64-linux-gnu/libssl.so.1.1
#10 0x00007f027703a2b3 in PySSL_dealloc (self=0x7f026bc4ecc0) at /home/debian/Python-3.10.10/Modules/_ssl.c:2219
#11 0x0000559d95fbe45d in _Py_Dealloc (op=<optimized out>) at ../Objects/object.c:2301
#12 0x0000559d96039376 in _Py_DECREF (op=<optimized out>, lineno=5899, filename=0x559d9623dcfb "../Python/ceval.c") at ../Include/object.h:500
#13 call_function (tstate=tstate@entry=0x7f026c41ce10, trace_info=trace_info@entry=0x7f0269ffb630, pp_stack=pp_stack@entry=0x7f0269ffb5d8, oparg=oparg@entry=2, kwnames=kwnames@entry=0x0) at ../Python/ceval.c:5899
#14 0x0000559d96046117 in _PyEval_EvalFrameDefault (tstate=0x7f026c41ce10, f=0x7f026c062250, throwflag=<optimized out>) at ../Python/ceval.c:4198
#15 0x0000559d96048848 in _PyEval_EvalFrame (throwflag=0, f=0x7f026c062250, tstate=0x7f026c41ce10) at ../Include/internal/pycore_ceval.h:46
#16 _PyEval_Vector (tstate=0x7f026c41ce10, con=0x7f0277073b80, locals=locals@entry=0x0, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at ../Python/ceval.c:5065
#17 0x0000559d95f82be9 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:342
#18 0x0000559d96034df0 in _PyObject_VectorcallTstate (tstate=0x7f026c41ce10, callable=0x7f0277073b70, args=0x7f026bf0af28, nargsf=9223372036854775810, kwnames=0x0) at ../Include/cpython/abstract.h:114
#19 0x0000559d96039335 in PyObject_Vectorcall (kwnames=0x0, nargsf=9223372036854775810, args=0x7f026bf0af28, callable=0x7f0277073b70) at ../Include/cpython/abstract.h:123
#20 call_function (tstate=tstate@entry=0x7f026c41ce10, trace_info=trace_info@entry=0x7f0269ffb870, pp_stack=pp_stack@entry=0x7f0269ffb818, oparg=oparg@entry=2, kwnames=kwnames@entry=0x0) at ../Python/ceval.c:5891
#21 0x0000559d96046117 in _PyEval_EvalFrameDefault (tstate=0x7f026c41ce10, f=0x7f026bf0ada0, throwflag=<optimized out>) at ../Python/ceval.c:4198
#22 0x0000559d96048848 in _PyEval_EvalFrame (throwflag=0, f=0x7f026bf0ada0, tstate=0x7f026c41ce10) at ../Include/internal/pycore_ceval.h:46
#23 _PyEval_Vector (tstate=0x7f026c41ce10, con=0x7f02770cc530, locals=locals@entry=0x0, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at ../Python/ceval.c:5065
#24 0x0000559d95f82be9 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:342
#25 0x0000559d96034df0 in _PyObject_VectorcallTstate (tstate=0x7f026c41ce10, callable=0x7f02770cc520, args=0x7f02692010c8, nargsf=9223372036854775810, kwnames=0x0) at ../Include/cpython/abstract.h:114
#26 0x0000559d96039335 in PyObject_Vectorcall (kwnames=0x0, nargsf=9223372036854775810, args=0x7f02692010c8, callable=0x7f02770cc520) at ../Include/cpython/abstract.h:123
#27 call_function (tstate=tstate@entry=0x7f026c41ce10, trace_info=trace_info@entry=0x7f0269ffbab0, pp_stack=pp_stack@entry=0x7f0269ffba58, oparg=oparg@entry=2, kwnames=kwnames@entry=0x0) at ../Python/ceval.c:5891
#28 0x0000559d96046117 in _PyEval_EvalFrameDefault (tstate=0x7f026c41ce10, f=0x7f0269200f30, throwflag=<optimized out>) at ../Python/ceval.c:4198
#29 0x0000559d96048848 in _PyEval_EvalFrame (throwflag=0, f=0x7f0269200f30, tstate=0x7f026c41ce10) at ../Include/internal/pycore_ceval.h:46
#30 _PyEval_Vector (tstate=0x7f026c41ce10, con=0x7f026bf7f550, locals=locals@entry=0x0, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at ../Python/ceval.c:5065
#31 0x0000559d95f82be9 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:342
#32 0x0000559d96034df0 in _PyObject_VectorcallTstate (tstate=0x7f026c41ce10, callable=0x7f026bf7f540, args=0x7f0269200e58, nargsf=9223372036854775808, kwnames=0x0) at ../Include/cpython/abstract.h:114
#33 0x0000559d96039335 in PyObject_Vectorcall (kwnames=0x0, nargsf=9223372036854775808, args=0x7f0269200e58, callable=0x7f026bf7f540) at ../Include/cpython/abstract.h:123
#34 call_function (tstate=tstate@entry=0x7f026c41ce10, trace_info=trace_info@entry=0x7f0269ffbcf0, pp_stack=pp_stack@entry=0x7f0269ffbca0, oparg=oparg@entry=0, kwnames=kwnames@entry=0x0) at ../Python/ceval.c:5891
#35 0x0000559d96046267 in _PyEval_EvalFrameDefault (tstate=0x7f026c41ce10, f=0x7f0269200cb0, throwflag=<optimized out>) at ../Python/ceval.c:4213
#36 0x0000559d96048848 in _PyEval_EvalFrame (throwflag=0, f=0x7f0269200cb0, tstate=0x7f026c41ce10) at ../Include/internal/pycore_ceval.h:46
#37 _PyEval_Vector (tstate=0x7f026c41ce10, con=0x7f02770cf760, locals=locals@entry=0x0, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at ../Python/ceval.c:5065
#38 0x0000559d95f82be9 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:342
#39 0x0000559d96034df0 in _PyObject_VectorcallTstate (tstate=0x7f026c41ce10, callable=0x7f02770cf750, args=0x7f026be9cee8, nargsf=9223372036854775810, kwnames=0x0) at ../Include/cpython/abstract.h:114
#40 0x0000559d96039335 in PyObject_Vectorcall (kwnames=0x0, nargsf=9223372036854775810, args=0x7f026be9cee8, callable=0x7f02770cf750) at ../Include/cpython/abstract.h:123
#41 call_function (tstate=tstate@entry=0x7f026c41ce10, trace_info=trace_info@entry=0x7f0269ffbf30, pp_stack=pp_stack@entry=0x7f0269ffbee0, oparg=oparg@entry=2, kwnames=kwnames@entry=0x0) at ../Python/ceval.c:5891
#42 0x0000559d96046267 in _PyEval_EvalFrameDefault (tstate=0x7f026c41ce10, f=0x7f026be9cd70, throwflag=<optimized out>) at ../Python/ceval.c:4213
#43 0x0000559d96048848 in _PyEval_EvalFrame (throwflag=0, f=0x7f026be9cd70, tstate=0x7f026c41ce10) at ../Include/internal/pycore_ceval.h:46
#44 _PyEval_Vector (tstate=0x7f026c41ce10, con=0x7f02770ed660, locals=locals@entry=0x0, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at ../Python/ceval.c:5065
#45 0x0000559d95f82be9 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:342
#46 0x0000559d9613a6ec in _PyObject_VectorcallTstate (tstate=0x7f026c41ce10, callable=0x7f02770ed650, args=0x7f026be9cd20, nargsf=2, kwnames=0x0) at ../Include/cpython/abstract.h:114
#47 0x0000559d9613af50 in method_vectorcall (method=<optimized out>, args=0x7f026be9cd28, nargsf=<optimized out>, kwnames=0x0) at ../Objects/classobject.c:53
#48 0x0000559d96034df0 in _PyObject_VectorcallTstate (tstate=0x7f026c41ce10, callable=0x7f026cac0590, args=0x7f026be9cd28, nargsf=9223372036854775809, kwnames=0x0) at ../Include/cpython/abstract.h:114
#49 0x0000559d96039335 in PyObject_Vectorcall (kwnames=0x0, nargsf=9223372036854775809, args=0x7f026be9cd28, callable=0x7f026cac0590) at ../Include/cpython/abstract.h:123
#50 call_function (tstate=tstate@entry=0x7f026c41ce10, trace_info=trace_info@entry=0x7f0269ffc230, pp_stack=pp_stack@entry=0x7f0269ffc1d8, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0) at ../Python/ceval.c:5891
#51 0x0000559d960461d6 in _PyEval_EvalFrameDefault (tstate=0x7f026c41ce10, f=0x7f026be9cb90, throwflag=<optimized out>) at ../Python/ceval.c:4181
#52 0x0000559d96048848 in _PyEval_EvalFrame (throwflag=0, f=0x7f026be9cb90, tstate=0x7f026c41ce10) at ../Include/internal/pycore_ceval.h:46
#53 _PyEval_Vector (tstate=0x7f026c41ce10, con=0x7f0277343080, locals=locals@entry=0x0, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at ../Python/ceval.c:5065
#54 0x0000559d95f82be9 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:342
#55 0x0000559d96034df0 in _PyObject_VectorcallTstate (tstate=0x7f026c41ce10, callable=0x7f0277343070, args=0x7f0269200bf0, nargsf=9223372036854775810, kwnames=0x0) at ../Include/cpython/abstract.h:114
#56 0x0000559d96039335 in PyObject_Vectorcall (kwnames=0x0, nargsf=9223372036854775810, args=0x7f0269200bf0, callable=0x7f0277343070) at ../Include/cpython/abstract.h:123
#57 call_function (tstate=tstate@entry=0x7f026c41ce10, trace_info=trace_info@entry=0x7f0269ffc470, pp_stack=pp_stack@entry=0x7f0269ffc418, oparg=oparg@entry=2, kwnames=kwnames@entry=0x0) at ../Python/ceval.c:5891
#58 0x0000559d96046117 in _PyEval_EvalFrameDefault (tstate=0x7f026c41ce10, f=0x7f0269200a30, throwflag=<optimized out>) at ../Python/ceval.c:4198
#59 0x0000559d96048848 in _PyEval_EvalFrame (throwflag=0, f=0x7f0269200a30, tstate=0x7f026c41ce10) at ../Include/internal/pycore_ceval.h:46
#60 _PyEval_Vector (tstate=0x7f026c41ce10, con=0x7f0277342bb0, locals=locals@entry=0x0, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at ../Python/ceval.c:5065
#61 0x0000559d95f82be9 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:342
#62 0x0000559d96034df0 in _PyObject_VectorcallTstate (tstate=0x7f026c41ce10, callable=0x7f0277342ba0, args=0x7f0269200980, nargsf=9223372036854775809, kwnames=0x0) at ../Include/cpython/abstract.h:114
#63 0x0000559d96039335 in PyObject_Vectorcall (kwnames=0x0, nargsf=9223372036854775809, args=0x7f0269200980, callable=0x7f0277342ba0) at ../Include/cpython/abstract.h:123
#64 call_function (tstate=tstate@entry=0x7f026c41ce10, trace_info=trace_info@entry=0x7f0269ffc6b0, pp_stack=pp_stack@entry=0x7f0269ffc658, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0) at ../Python/ceval.c:5891
#65 0x0000559d96046117 in _PyEval_EvalFrameDefault (tstate=0x7f026c41ce10, f=0x7f02692007b0, throwflag=<optimized out>) at ../Python/ceval.c:4198
#66 0x0000559d96048848 in _PyEval_EvalFrame (throwflag=0, f=0x7f02692007b0, tstate=0x7f026c41ce10) at ../Include/internal/pycore_ceval.h:46
#67 _PyEval_Vector (tstate=0x7f026c41ce10, con=0x7f0277342fd0, locals=locals@entry=0x0, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at ../Python/ceval.c:5065
#68 0x0000559d95f82be9 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:342
#69 0x0000559d96034df0 in _PyObject_VectorcallTstate (tstate=0x7f026c41ce10, callable=0x7f0277342fc0, args=0x7f026c06e840, nargsf=9223372036854775809, kwnames=0x0) at ../Include/cpython/abstract.h:114
--Type <RET> for more, q to quit, c to continue without paging--
#70 0x0000559d96039335 in PyObject_Vectorcall (kwnames=0x0, nargsf=9223372036854775809, args=0x7f026c06e840, callable=0x7f0277342fc0) at ../Include/cpython/abstract.h:123
#71 call_function (tstate=tstate@entry=0x7f026c41ce10, trace_info=trace_info@entry=0x7f0269ffc8f0, pp_stack=pp_stack@entry=0x7f0269ffc898, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0) at ../Python/ceval.c:5891
#72 0x0000559d96046117 in _PyEval_EvalFrameDefault (tstate=0x7f026c41ce10, f=0x7f026c06e6d0, throwflag=<optimized out>) at ../Python/ceval.c:4198
#73 0x0000559d96048848 in _PyEval_EvalFrame (throwflag=0, f=0x7f026c06e6d0, tstate=0x7f026c41ce10) at ../Include/internal/pycore_ceval.h:46
#74 _PyEval_Vector (tstate=0x7f026c41ce10, con=0x7f02770ed240, locals=locals@entry=0x0, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at ../Python/ceval.c:5065
#75 0x0000559d95f82be9 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:342
#76 0x0000559d96034df0 in _PyObject_VectorcallTstate (tstate=0x7f026c41ce10, callable=0x7f02770ed230, args=0x7f026bf09960, nargsf=9223372036854775809, kwnames=0x0) at ../Include/cpython/abstract.h:114
#77 0x0000559d96039335 in PyObject_Vectorcall (kwnames=0x0, nargsf=9223372036854775809, args=0x7f026bf09960, callable=0x7f02770ed230) at ../Include/cpython/abstract.h:123
#78 call_function (tstate=tstate@entry=0x7f026c41ce10, trace_info=trace_info@entry=0x7f0269ffcb30, pp_stack=pp_stack@entry=0x7f0269ffcad8, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0) at ../Python/ceval.c:5891
#79 0x0000559d96046117 in _PyEval_EvalFrameDefault (tstate=0x7f026c41ce10, f=0x7f026bf097e0, throwflag=<optimized out>) at ../Python/ceval.c:4198
#80 0x0000559d96048848 in _PyEval_EvalFrame (throwflag=0, f=0x7f026bf097e0, tstate=0x7f026c41ce10) at ../Include/internal/pycore_ceval.h:46
#81 _PyEval_Vector (tstate=0x7f026c41ce10, con=0x7f02770ed190, locals=locals@entry=0x0, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at ../Python/ceval.c:5065
#82 0x0000559d95f82be9 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:342
#83 0x0000559d96034df0 in _PyObject_VectorcallTstate (tstate=0x7f026c41ce10, callable=0x7f02770ed180, args=0x7f02692006e8, nargsf=9223372036854775809, kwnames=0x0) at ../Include/cpython/abstract.h:114
#84 0x0000559d96039335 in PyObject_Vectorcall (kwnames=0x0, nargsf=9223372036854775809, args=0x7f02692006e8, callable=0x7f02770ed180) at ../Include/cpython/abstract.h:123
#85 call_function (tstate=tstate@entry=0x7f026c41ce10, trace_info=trace_info@entry=0x7f0269ffcd70, pp_stack=pp_stack@entry=0x7f0269ffcd18, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0) at ../Python/ceval.c:5891
#86 0x0000559d96046117 in _PyEval_EvalFrameDefault (tstate=0x7f026c41ce10, f=0x7f0269200530, throwflag=<optimized out>) at ../Python/ceval.c:4198
#87 0x0000559d96048848 in _PyEval_EvalFrame (throwflag=0, f=0x7f0269200530, tstate=0x7f026c41ce10) at ../Include/internal/pycore_ceval.h:46
#88 _PyEval_Vector (tstate=0x7f026c41ce10, con=0x7f0276cec110, locals=locals@entry=0x0, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at ../Python/ceval.c:5065
#89 0x0000559d95f82be9 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:342
#90 0x0000559d9613afcf in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=1, args=0x7f0269ffce68, callable=0x7f0276cec100, tstate=0x7f026c41ce10) at ../Include/cpython/abstract.h:114
#91 method_vectorcall (method=<optimized out>, args=0x7f0281c08268, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/classobject.c:61
#92 0x0000559d95f82807 in PyVectorcall_Call (callable=callable@entry=0x7f026cb14c50, tuple=tuple@entry=0x7f0281c08250, kwargs=kwargs@entry=0x7f026d49e9f0) at ../Objects/call.c:255
#93 0x0000559d95f82b06 in _PyObject_Call (tstate=0x7f026c41ce10, callable=callable@entry=0x7f026cb14c50, args=args@entry=0x7f0281c08250, kwargs=kwargs@entry=0x7f026d49e9f0) at ../Objects/call.c:290
#94 0x0000559d95f82b6f in PyObject_Call (callable=callable@entry=0x7f026cb14c50, args=args@entry=0x7f0281c08250, kwargs=kwargs@entry=0x7f026d49e9f0) at ../Objects/call.c:317
#95 0x0000559d9603961f in do_call_core (tstate=tstate@entry=0x7f026c41ce10, trace_info=trace_info@entry=0x7f0269ffd070, func=func@entry=0x7f026cb14c50, callargs=callargs@entry=0x7f0281c08250, kwdict=kwdict@entry=0x7f026d49e9f0) at ../Python/ceval.c:5943
#96 0x0000559d96046727 in _PyEval_EvalFrameDefault (tstate=0x7f026c41ce10, f=0x7f026bf090a0, throwflag=<optimized out>) at ../Python/ceval.c:4277
#97 0x0000559d96048848 in _PyEval_EvalFrame (throwflag=0, f=0x7f026bf090a0, tstate=0x7f026c41ce10) at ../Include/internal/pycore_ceval.h:46
#98 _PyEval_Vector (tstate=0x7f026c41ce10, con=0x7f0280c39d40, locals=locals@entry=0x0, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at ../Python/ceval.c:5065
#99 0x0000559d95f82be9 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:342
#100 0x0000559d96034df0 in _PyObject_VectorcallTstate (tstate=0x7f026c41ce10, callable=0x7f0280c39d30, args=0x7f02692001a0, nargsf=9223372036854775809, kwnames=0x0) at ../Include/cpython/abstract.h:114
#101 0x0000559d96039335 in PyObject_Vectorcall (kwnames=0x0, nargsf=9223372036854775809, args=0x7f02692001a0, callable=0x7f0280c39d30) at ../Include/cpython/abstract.h:123
#102 call_function (tstate=tstate@entry=0x7f026c41ce10, trace_info=trace_info@entry=0x7f0269ffd2b0, pp_stack=pp_stack@entry=0x7f0269ffd258, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0) at ../Python/ceval.c:5891
#103 0x0000559d96046117 in _PyEval_EvalFrameDefault (tstate=0x7f026c41ce10, f=0x7f0269200030, throwflag=<optimized out>) at ../Python/ceval.c:4198
#104 0x0000559d96048848 in _PyEval_EvalFrame (throwflag=0, f=0x7f0269200030, tstate=0x7f026c41ce10) at ../Include/internal/pycore_ceval.h:46
#105 _PyEval_Vector (tstate=0x7f026c41ce10, con=0x7f0280c3a0b0, locals=locals@entry=0x0, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at ../Python/ceval.c:5065
#106 0x0000559d95f82be9 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:342
#107 0x0000559d96034df0 in _PyObject_VectorcallTstate (tstate=0x7f026c41ce10, callable=0x7f0280c3a0a0, args=0x7f026bf09040, nargsf=9223372036854775809, kwnames=0x0) at ../Include/cpython/abstract.h:114
#108 0x0000559d96039335 in PyObject_Vectorcall (kwnames=0x0, nargsf=9223372036854775809, args=0x7f026bf09040, callable=0x7f0280c3a0a0) at ../Include/cpython/abstract.h:123
#109 call_function (tstate=tstate@entry=0x7f026c41ce10, trace_info=trace_info@entry=0x7f0269ffd4f0, pp_stack=pp_stack@entry=0x7f0269ffd498, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0) at ../Python/ceval.c:5891
#110 0x0000559d96046117 in _PyEval_EvalFrameDefault (tstate=0x7f026c41ce10, f=0x7f026bf08ed0, throwflag=<optimized out>) at ../Python/ceval.c:4198
#111 0x0000559d96048848 in _PyEval_EvalFrame (throwflag=0, f=0x7f026bf08ed0, tstate=0x7f026c41ce10) at ../Include/internal/pycore_ceval.h:46
#112 _PyEval_Vector (tstate=0x7f026c41ce10, con=0x7f0280c39df0, locals=locals@entry=0x0, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at ../Python/ceval.c:5065
#113 0x0000559d95f82be9 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:342
#114 0x0000559d9613afcf in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=1, args=0x7f0269ffd5e8, callable=0x7f0280c39de0, tstate=0x7f026c41ce10) at ../Include/cpython/abstract.h:114
#115 method_vectorcall (method=<optimized out>, args=0x7f0281c08268, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/classobject.c:61
#116 0x0000559d95f82807 in PyVectorcall_Call (callable=callable@entry=0x7f026cb17830, tuple=tuple@entry=0x7f0281c08250, kwargs=kwargs@entry=0x0) at ../Objects/call.c:255
#117 0x0000559d95f82b06 in _PyObject_Call (tstate=0x7f026c41ce10, callable=0x7f026cb17830, args=0x7f0281c08250, kwargs=0x0) at ../Objects/call.c:290
#118 0x0000559d95f82b6f in PyObject_Call (callable=<optimized out>, args=<optimized out>, kwargs=<optimized out>) at ../Objects/call.c:317
#119 0x0000559d960fd9f1 in thread_run (boot_raw=boot_raw@entry=0x7f026ca8ec00) at ../Modules/_threadmodule.c:1100
#120 0x0000559d9609b77c in pythread_wrapper (arg=<optimized out>) at ../Python/thread_pthread.h:248
#121 0x00007f0282272ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#122 0x00007f0282043a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) source python_installs/python-3.10.10-debug/bin/python3.10-gdb.py 
(gdb) py-bt
Traceback (most recent call first):
  File "/home/debian/python_installs/python-3.10.10-debug/lib/python3.10/ssl.py", line 1132, in read
    return self._sslobj.read(len)
  File "/home/debian/python_installs/python-3.10.10-debug/lib/python3.10/ssl.py", line 1259, in recv
    return self.read(buflen)
  File "/usr/lib/python3.10/site-packages/websocket/_socket.py", line 87, in _recv
    return sock.recv(bufsize)
  File "/usr/lib/python3.10/site-packages/websocket/_socket.py", line 108, in recv
    bytes_ = _recv()
  File "/usr/lib/python3.10/site-packages/websocket/_core.py", line 529, in _recv
    return recv(self.sock, bufsize)
  File "/usr/lib/python3.10/site-packages/websocket/_abnf.py", line 373, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/lib/python3.10/site-packages/websocket/_abnf.py", line 294, in recv_header
    header = self.recv_strict(2)
  File "/usr/lib/python3.10/site-packages/websocket/_abnf.py", line 338, in recv_frame
    self.recv_header()
  File "/usr/lib/python3.10/site-packages/websocket/_core.py", line 445, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/lib/python3.10/site-packages/websocket/_core.py", line 406, in recv_data_frame
    frame = self.recv_frame()
  File "/home/debian/my_script.py", line 2557, in __websocket_callback
    op_code, frame = ws.recv_data_frame()
  File "/home/debian/python_installs/python-3.10.10-debug/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/debian/python_installs/python-3.10.10-debug/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/debian/python_installs/python-3.10.10-debug/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
```

Just before the SIGSEGV the script triggered a timer reconnection 

```
[04-17-2023_14-29-31.474250] [RECONNECT-TIMER] Timer triggered on <websocket._core.WebSocket object at 0x7f026ca8e6c0>
[04-17-2023_14-29-31.474311] [RECONNECT] Reconnecting on <websocket._core.WebSocket object at 0x7f026ca8e6c0>
/usr/lib/python3.10/site-packages/websocket/_core.py:249: ResourceWarning: unclosed <ssl.SSLSocket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.31.29.22', 52678), raddr=('193.73.250.190', 443)>
  self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

Does anybody knows where this issue could come from ? 

I could understand facing an exception but a segmentation fault seems to come from lower level code.

**Comment by engn33r** [comment]
Are you working with websockets that are have high data throughput, many connections, long connection times, or are connecting to many different websocket servers? #837 mentions such edge cases have not been tested thoroughly yet.

Looking at your error log, I see two items that look like common points of failure. One is the ssl resource warning in the script timer reconnection log. SSL is not handled by websocket-client, it is handled at a low level by Python. If you search for "ssl" you will find past issues where ssl is the problem. The other item I noticed is the first line of the traceback is for the file ssl.py. This indicates an SSL problem that is not in scope of websocket-client.

Let us know if you find a solution. It is possible there is an issue in _socket.py with how the ssl connection data is received, but past ssl-related issues normally relate to ssl and not websocket-client.
