### ISSUE TITLE
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2423)

### ISSUE THREAD

**Issue by ljsbtx** [websocket-client/websocket-client#922]
Job "ws_ping (trigger: interval[0:00:20], next run at: 2023-06-19 22:12:07 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/__init__.py", line 100, in ws_ping
    ws.send('ping')
  File "/usr/local/lib/python3.11/site-packages/websocket/_core.py", line 283, in send
    return self.send_frame(frame)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websocket/_core.py", line 311, in send_frame
    l = self._send(data)
        ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websocket/_core.py", line 525, in _send
    return send(self.sock, data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websocket/_socket.py", line 170, in send
    return _send()
           ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websocket/_socket.py", line 147, in _send
    return sock.send(data)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1210, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2423)

**Comment by engn33r** [comment]
Previous issues reported here containing the line EOF or similar SSL errors are usually SSL issues rather than websocket-client issues. Are you able to share the SSL options you are using for the connection? If you control the server, check what SSL requirements are being specified by the server.

For more information, try searching past websocket-client issues for the word SSL and you might find answers in old issues such as #744 or #693.
