### ISSUE TITLE
WebSocketBadStatusException: Handshake status 403 Forbidden -+-+- 

### ISSUE THREAD

**Issue by QuXing9** [websocket-client/websocket-client#939]
## Description
Hello, I want to debug an H5 page on an Android app, But When I connect the webSocketDebuggerUrl using websocket, it reports an error `WebSocketBadStatusException: Handshake status 403 Forbidden -+-+- `. May I ask how to resolve this error? 
## Reproduce
1. Connect an Android phone to my Windows computer.
2. Enable developer mode on the phone.
3. Type chrome://inspect in the Chrome browser, it shows the webview pages. Type the `inspect` link, it opens a devtools and shows the webview page correctly.
![image](https://github.com/websocket-client/websocket-client/assets/40267809/d9d4d771-49e3-42b2-ad6a-eefa3b36bebf)
4. Forward socket process to computer, using command `adb forward tcp:9222 localabstract::webview_devtools_remote_17180`.
5. Type http://localhost:9225/json in the Chrome browser, it shows an list.
6. connect the webSocketDebuggerUrl in the list
```
import websocket
ws = websocket.WebSocket()
ws.connect("ws://localhost:9225/devtools/page/625C5EB348BF3D8E0B359614B7003DE3")
```
7. it reports an error
```
>>> ws.connect("ws://localhost:9225/devtools/page/625C5EB348BF3D8E0B359614B7003DE3")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\work\MiniConda\lib\site-packages\websocket\_core.py", line 253, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "D:\work\MiniConda\lib\site-packages\websocket\_handshake.py", line 57, in handshake
    status, resp = _get_resp_headers(sock)
  File "D:\work\MiniConda\lib\site-packages\websocket\_handshake.py", line 150, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status {status} {message} -+-+- {headers} -+-+- {body}".format(status=status, message=status_message, headers=resp_headers, body=response_body), status, status_message, resp_headers, response_body)
websocket._exceptions.WebSocketBadStatusException: Handshake status 403 Forbidden -+-+- {'content-length': '239', 'content-type': 'text/html'} -+-+- b'Rejected an incoming WebSocket connection from the http://localhost:9224 origin. Use the command line flag --remote-allow-origins=http://localhost:9224 to allow connections from this origin or --remote-allow-origins=* to allow all origins.'
```
Based on the error message, it seems to be related to the permissions for debugging webviews, but I'm not sure.
## version
websocket==0.2.1
websocket-client==1.6.1

**Comment by QuXing9** [comment]
solved, it's a problem with the app's browser engine.
