### ISSUE TITLE
websocket-client is not wokring with flask_socketio ?

### ISSUE THREAD

**Issue by erikpa1** [websocket-client/websocket-client#954]
Hi, I'm trying to connect this library with Flask

```
from flask_socketio import SocketIO
from flask_cors import CORS

from flask import Flask

app = Flask("MyName", static_url_path='')
ws = SocketIO(app, cors_allowed_origins="*", async_mode="threading")

cors = CORS(app, resources={r"/socket.io/*": {"origins": "*"}})

ws.run(app=app, debug=True, host="0.0.0.0", allow_unsafe_werkzeug=True)
```

In client side, everything works fine, using:
https://www.npmjs.com/package/socket.io-client

Also your cryptocurrency examples works well.

But on my python socket client I got errors like:

```
Traceback (most recent call last):
  File "E:\Work\vts_web_gui\socket client\main.py", line 36, in <module>
    ws = create_connection("ws://localhost:5000/socket.io")
  File "E:\Work\Ella\Libraries\Python\python-3.7.6.amd64\lib\site-packages\websocket\_core.py", line 608, in create_connection
    websock.connect(url, **options)
  File "E:\Work\Ella\Libraries\Python\python-3.7.6.amd64\lib\site-packages\websocket\_core.py", line 253, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "E:\Work\Ella\Libraries\Python\python-3.7.6.amd64\lib\site-packages\websocket\_handshake.py", line 57, in handshake
    status, resp = _get_resp_headers(sock)
  File "E:\Work\Ella\Libraries\Python\python-3.7.6.amd64\lib\site-packages\websocket\_handshake.py", line 150, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status {status} {message} -+-+- {headers} -+-+- {body}".format(status=status, message=status_message, headers=resp_headers, body=response_body), status, status_message, resp_headers, response_body)
websocket._exceptions.WebSocketBadSt

```

```
--- request header ---
GET /socket.io/?transport=websocket HTTP/1.1
Upgrade: websocket
Host: localhost:5000
Origin: http://localhost:5000
Sec-WebSocket-Key: TtrDXJUPclUVlIKQKjmw6A==
Sec-WebSocket-Version: 13
Connection: Upgrade


-----------------------
--- response header ---
HTTP/1.1 400 BAD REQUEST
Server: Werkzeug/2.3.7 Python/3.11.2
Date: Thu, 26 Oct 2023 15:05:11 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: close
-----------------------
Handshake status 400 BAD REQUEST -+-+- {'server': 'Werkzeug/2.3.7 Python/3.11.2', 'date': 'Thu, 26 Oct 2023 15:05:11 GMT', 'content-type': 'text/plain', 'transfer-encoding': 'chunked', 'connection': 'close'} -+-+- None - reconnect
Handshake status 400 BAD REQUEST -+-+- {'server': 'Werkzeug/2.3.7 Python/3.11.2', 'date': 'Thu, 26 Oct 2023 15:05:11 GMT', 'content-type': 'text/plain', 'transfer-encoding': 'chunked', 'connection': 'close'} -+-+- None
Calling dispatcher reconnect [2 frames in stack]
reconnect() - retrying in 5 seconds [3 frames in stack]

```

also tried: `"ws://localhost:5000/socket.io/?transport=websocket"`, any combination... I'm using 

Flask-SocketIO==5.3.6
Flask==2.2.5
Python 3.11

Any Idea ?

**Comment by erikpa1** [comment]
Nah ok, now I understand, WebSocket and SOcketIO are 2 different things.....
